### ISSUE TITLE
Multichain-Explorer has an http time out issue?

### ISSUE THREAD

**Issue by JarBinks** [asc-lab/blockchain-multichain#1]
When building the stack I get the error below and the multichain-explorer is not running.

Any hints?

![image](https://user-images.githubusercontent.com/18104455/50853567-8d460b00-1350-11e9-8c38-8375b085ecb2.png)

**Comment by witek1902** [comment]
Some days ago in `multichain-explorer` project has been added new python library `py-ubjson`.
https://github.com/MultiChain/multichain-explorer/pull/45

We add in our `Dockerfile` this library and after commit e63b72e everything should work correctly :)
